/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectGUI;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ribka Restu
 */
public class BatalMisa extends javax.swing.JFrame {

    public static ArrayList<Jadwal> jadwalTerupdate = DaftarMisa.jadwalTerupdate;

    /**
     * Creates new form HalamanUtama
     */
    public BatalMisa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Batalkan misa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelLogo = new javax.swing.JPanel();
        jLabelLogoHU = new javax.swing.JLabel();
        jPanelFormLogin = new javax.swing.JPanel();
        jLabelLogoHU1 = new javax.swing.JLabel();
        jButtonKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKodeMisa = new javax.swing.JTextField();
        jButtonBatalMisa = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogo.setBackground(new java.awt.Color(51, 0, 0));
        jPanelLogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo HU_.png"))); // NOI18N
        jPanelLogo.add(jLabelLogoHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(jPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        jPanelFormLogin.setBackground(new java.awt.Color(102, 0, 0));
        jPanelFormLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoHU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo HU_.png"))); // NOI18N
        jPanelFormLogin.add(jLabelLogoHU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -60, -1, -1));

        jButtonKembali.setText("KEMBALI");
        jButtonKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonKembaliMouseClicked(evt);
            }
        });
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        jPanelFormLogin.add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masukkan kode misa :");
        jPanelFormLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, -1));
        jPanelFormLogin.add(jTextFieldKodeMisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 300, 30));

        jButtonBatalMisa.setText("BATAL MISA");
        jButtonBatalMisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatalMisaMouseClicked(evt);
            }
        });
        jButtonBatalMisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalMisaActionPerformed(evt);
            }
        });
        jPanelFormLogin.add(jButtonBatalMisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 120, -1));

        getContentPane().add(jPanelFormLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonBatalMisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatalMisaMouseClicked
        // TODO add your handling code here:
        batal();
        jTextFieldKodeMisa.setText("");

    }//GEN-LAST:event_jButtonBatalMisaMouseClicked

    private void jButtonKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKembaliMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanUtamaUmat().setVisible(true);
    }//GEN-LAST:event_jButtonKembaliMouseClicked

    private void jButtonBatalMisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalMisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBatalMisaActionPerformed
    public void batal() {
        String hapus = jTextFieldKodeMisa.getText();
        Umat hapusUmat = new Umat(hapus);
        TreeNode<Umat> cariHapus = null;
        int indeksHapus = 0;
        for (int i = 0; i < jadwalTerupdate.size(); i++) {
            if (jadwalTerupdate.get(i).getUmat().getCurrent(hapusUmat) != null) {
                cariHapus = jadwalTerupdate.get(i).getUmat().getCurrent(hapusUmat);
                indeksHapus = i;
                break;
            }
        }
        if (cariHapus != null) {
            int tampung = JOptionPane.showConfirmDialog(null, "Atas nama  " + cariHapus.getData().getNama() + " ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (tampung == JOptionPane.YES_OPTION) {
                int tampung2 = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin membatalkan misa"
                        + "? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (tampung2 == JOptionPane.YES_OPTION) {
                    jadwalTerupdate.get(indeksHapus).getUmat().delete(hapusUmat);
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    jadwalTerupdate.get(indeksHapus).setKuota(jadwalTerupdate.get(indeksHapus).getKuota() + 1);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatalMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatalMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatalMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatalMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BatalMisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatalMisa;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogoHU;
    private javax.swing.JLabel jLabelLogoHU1;
    private javax.swing.JPanel jPanelFormLogin;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldKodeMisa;
    // End of variables declaration//GEN-END:variables
}
