/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectGUI;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ribka Restu
 */
public class DaftarMisa extends javax.swing.JFrame {

    public static ArrayList<Jadwal> jadwalTerupdate = KosongkanJadwal.jadwalKosong;
    static int createId = 99;

    /**
     * Creates new form HalamanUtama
     */
    public DaftarMisa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Daftar Misa");
        String temp1 = "";
        DefaultComboBoxModel mdl = new DefaultComboBoxModel();
        jComboBoxJadwalMisa.setModel(mdl);
        for (int i = 0; i < jadwalTerupdate.size(); i++) {
            mdl.addElement((i + 1) + ". " + jadwalTerupdate.get(i).getHari() + " " + jadwalTerupdate.get(i).getJam());
        }
        jTextAreaInfoMisa.setText("Tanggal : " + jadwalTerupdate.get(0).getTanggal() + "\nKuota : " + jadwalTerupdate.get(0).getKuota() + "\nImam : " + jadwalTerupdate.get(0).getImam());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelLogo = new javax.swing.JPanel();
        jLabelLogoHU = new javax.swing.JLabel();
        jPanelFormLogin = new javax.swing.JPanel();
        jLabelLogoHU1 = new javax.swing.JLabel();
        jButtonKembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxJadwalMisa = new javax.swing.JComboBox<>();
        jButtonDaftar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInfoMisa = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogo.setBackground(new java.awt.Color(51, 0, 0));
        jPanelLogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo HU_.png"))); // NOI18N
        jPanelLogo.add(jLabelLogoHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        getContentPane().add(jPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        jPanelFormLogin.setBackground(new java.awt.Color(102, 0, 0));
        jPanelFormLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoHU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo HU_.png"))); // NOI18N
        jPanelFormLogin.add(jLabelLogoHU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -60, -1, -1));

        jButtonKembali.setText("KEMBALI");
        jButtonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKembaliActionPerformed(evt);
            }
        });
        jPanelFormLogin.add(jButtonKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masukkan nama (panggilan) anda :");
        jPanelFormLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 290, 20));
        jPanelFormLogin.add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 300, 30));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Masukkan alamat :");
        jPanelFormLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 290, -1));
        jPanelFormLogin.add(jTextFieldAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 300, 30));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pilih jadwal misa :");
        jPanelFormLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jComboBoxJadwalMisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJadwalMisaActionPerformed(evt);
            }
        });
        jPanelFormLogin.add(jComboBoxJadwalMisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 300, -1));

        jButtonDaftar.setText("DAFTAR");
        jButtonDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDaftarMouseClicked(evt);
            }
        });
        jPanelFormLogin.add(jButtonDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 90, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaInfoMisa.setColumns(20);
        jTextAreaInfoMisa.setRows(5);
        jTextAreaInfoMisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Keterangan"));
        jScrollPane2.setViewportView(jTextAreaInfoMisa);

        jPanelFormLogin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 300, 90));

        getContentPane().add(jPanelFormLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HalamanUtamaUmat().setVisible(true);
    }//GEN-LAST:event_jButtonKembaliActionPerformed

    private void jButtonDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDaftarMouseClicked
        // TODO add your handling code here:
        if (jTextFieldNama.getText().equals("") || jTextFieldAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap lengkapi data!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            daftar();
            jTextAreaInfoMisa.setText("Tanggal : " + jadwalTerupdate.get(0).getTanggal() + "\nKuota : " + jadwalTerupdate.get(0).getKuota() + "\nImam : " + jadwalTerupdate.get(0).getImam());
            jTextFieldNama.setText("");
            jTextFieldAlamat.setText("");
            jComboBoxJadwalMisa.setSelectedIndex(0);
        }


    }//GEN-LAST:event_jButtonDaftarMouseClicked

    private void jComboBoxJadwalMisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJadwalMisaActionPerformed
        // TODO add your handling code here:
        int pilih = jComboBoxJadwalMisa.getSelectedIndex();
        jTextAreaInfoMisa.setText("Tanggal : " + jadwalTerupdate.get(pilih).getTanggal() + "\nKuota : " + jadwalTerupdate.get(pilih).getKuota() + "\nImam : " + jadwalTerupdate.get(pilih).getImam());


    }//GEN-LAST:event_jComboBoxJadwalMisaActionPerformed
    public void daftar() {
        String nama, alamat, id;
        int pilihMisa;
        nama = jTextFieldNama.getText();
        alamat = jTextFieldAlamat.getText();
        pilihMisa = jComboBoxJadwalMisa.getSelectedIndex();
        createId++;
        id = "G-" + createId;
        int jumlahNode = jadwalTerupdate.get(pilihMisa).getUmat().countNodes(jadwalTerupdate.get(pilihMisa).getUmat().getRoot());
        if (jumlahNode < jadwalTerupdate.get(pilihMisa).getKuota()) {
            jadwalTerupdate.get(pilihMisa).getUmat().insert(new Umat(nama, alamat, id));
            jadwalTerupdate.get(pilihMisa).setKuota(jadwalTerupdate.get(pilihMisa).getKuota() - 1);
            JOptionPane.showMessageDialog(null, "Kode pendaftaran kamu adalah " + id + ""
                    + "!\nSilahkan simpan untuk ditunjukan pada petugas, terima kasih.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Kuota penuh !", "Gagal mendaftar", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarMisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarMisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDaftar;
    private javax.swing.JButton jButtonKembali;
    private javax.swing.JComboBox<String> jComboBoxJadwalMisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLogoHU;
    private javax.swing.JLabel jLabelLogoHU1;
    private javax.swing.JPanel jPanelFormLogin;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaInfoMisa;
    private javax.swing.JTextField jTextFieldAlamat;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
