/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectGUI;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Ribka Restu
 */
public class HalamanUtamaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtamaAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Halaman Utama Admin");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelLogo = new javax.swing.JPanel();
        jLabelLogoHU = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPanduan = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanelFormLogin = new javax.swing.JPanel();
        jLabelLogoHU1 = new javax.swing.JLabel();
        jLabelCariDataUmat = new javax.swing.JLabel();
        jLabelLihatDataUmat = new javax.swing.JLabel();
        jLabelTambahJadwalMisa = new javax.swing.JLabel();
        jLabelHapusJadwalMisa = new javax.swing.JLabel();
        jLabelKosongkanJadwalMisa = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogo.setBackground(new java.awt.Color(51, 0, 0));
        jPanelLogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo HU_.png"))); // NOI18N
        jPanelLogo.add(jLabelLogoHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Kozuka Mincho Pr6N M", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(220, 150, 0));
        jLabel5.setText("GEREJA SANTO ALOYSIUS KALEMBU PANETA");
        jPanelLogo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        getContentPane().add(jPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextAreaPanduan.setEditable(false);
        jTextAreaPanduan.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaPanduan.setColumns(20);
        jTextAreaPanduan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextAreaPanduan.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaPanduan.setLineWrap(true);
        jTextAreaPanduan.setRows(5);
        jTextAreaPanduan.setText("Dalam aplikasi ini terdapat beberapa menu yang bisa anda gunakan, yaitu :\n1. Cari Data umat\n    Gunakan fitur ini jika anda ingin mengecek apakah umat yang hendak mengikuti misa sudah  \n    mendaftar atau belum.\n\n2.  Lihat Data Umat\n     Gunakan fitur ini jika ingin melihat daftar umat yang telah mendaftar di masing-masing jadwal.\n\n3. Tambah Jadwal Misa\n     Gunakan fitur ini jika anda ingin menambahkan jadwal misa.\n\n4. Hapus jadwal misa\n   Gunakan fitur ini jika anda ingin menghapus salah satu jadwal misa saja.\n\n5. Kosongkan jadwal misa\n    Gunakan fitur ini jika anda ingin menhapus semua jadwal misa");
        jTextAreaPanduan.setWrapStyleWord(true);
        jTextAreaPanduan.setBorder(javax.swing.BorderFactory.createTitledBorder("Panduan"));
        jTextAreaPanduan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextAreaPanduan.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTextAreaPanduan);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Perhatian !!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 510, 350));

        jPanelFormLogin.setBackground(new java.awt.Color(102, 0, 0));
        jPanelFormLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoHU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo HU_.png"))); // NOI18N
        jPanelFormLogin.add(jLabelLogoHU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -70, -1, -1));

        jLabelCariDataUmat.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCariDataUmat.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabelCariDataUmat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCariDataUmat.setText("> Cari Data Umat");
        jLabelCariDataUmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCariDataUmatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCariDataUmatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCariDataUmatMouseExited(evt);
            }
        });
        jPanelFormLogin.add(jLabelCariDataUmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabelLihatDataUmat.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabelLihatDataUmat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLihatDataUmat.setText("> Lihat Data Umat");
        jLabelLihatDataUmat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLihatDataUmatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLihatDataUmatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLihatDataUmatMouseExited(evt);
            }
        });
        jPanelFormLogin.add(jLabelLihatDataUmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabelTambahJadwalMisa.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabelTambahJadwalMisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTambahJadwalMisa.setText(">Tambah Jadwal Misa");
        jLabelTambahJadwalMisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTambahJadwalMisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTambahJadwalMisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTambahJadwalMisaMouseExited(evt);
            }
        });
        jPanelFormLogin.add(jLabelTambahJadwalMisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabelHapusJadwalMisa.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabelHapusJadwalMisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHapusJadwalMisa.setText(">Hapus Jadwal Misa");
        jLabelHapusJadwalMisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHapusJadwalMisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHapusJadwalMisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelHapusJadwalMisaMouseExited(evt);
            }
        });
        jPanelFormLogin.add(jLabelHapusJadwalMisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabelKosongkanJadwalMisa.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabelKosongkanJadwalMisa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelKosongkanJadwalMisa.setText("> Kosongkan Jadwal Misa");
        jLabelKosongkanJadwalMisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKosongkanJadwalMisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelKosongkanJadwalMisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelKosongkanJadwalMisaMouseExited(evt);
            }
        });
        jPanelFormLogin.add(jLabelKosongkanJadwalMisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabelHome.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(220, 150, 0));
        jLabelHome.setText(">Home");
        jPanelFormLogin.add(jLabelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButtonLogout.setText("LOGOUT");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanelFormLogin.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        getContentPane().add(jPanelFormLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCariDataUmatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCariDataUmatMouseEntered
        // TODO add your handling code here:
        jLabelCariDataUmat.setForeground(new Color(220, 150, 0));
    }//GEN-LAST:event_jLabelCariDataUmatMouseEntered

    private void jLabelCariDataUmatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCariDataUmatMouseExited
        // TODO add your handling code here:
        jLabelCariDataUmat.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelCariDataUmatMouseExited

    private void jLabelLihatDataUmatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLihatDataUmatMouseEntered
        // TODO add your handling code here:
        jLabelLihatDataUmat.setForeground(new Color(220, 150, 0));
    }//GEN-LAST:event_jLabelLihatDataUmatMouseEntered

    private void jLabelLihatDataUmatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLihatDataUmatMouseExited
        // TODO add your handling code here:
        jLabelLihatDataUmat.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelLihatDataUmatMouseExited

    private void jLabelTambahJadwalMisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTambahJadwalMisaMouseEntered
        // TODO add your handling code here:
        jLabelTambahJadwalMisa.setForeground(new Color(220, 150, 0));
    }//GEN-LAST:event_jLabelTambahJadwalMisaMouseEntered

    private void jLabelTambahJadwalMisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTambahJadwalMisaMouseExited
        // TODO add your handling code here:
        jLabelTambahJadwalMisa.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelTambahJadwalMisaMouseExited

    private void jLabelHapusJadwalMisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHapusJadwalMisaMouseEntered
        // TODO add your handling code here:
        jLabelHapusJadwalMisa.setForeground(new Color(220, 150, 0));
    }//GEN-LAST:event_jLabelHapusJadwalMisaMouseEntered

    private void jLabelHapusJadwalMisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHapusJadwalMisaMouseExited
        // TODO add your handling code here:
        jLabelHapusJadwalMisa.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelHapusJadwalMisaMouseExited

    private void jLabelKosongkanJadwalMisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKosongkanJadwalMisaMouseEntered
        // TODO add your handling code here:
        jLabelKosongkanJadwalMisa.setForeground(new Color(220, 150, 0));
    }//GEN-LAST:event_jLabelKosongkanJadwalMisaMouseEntered

    private void jLabelKosongkanJadwalMisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKosongkanJadwalMisaMouseExited
        // TODO add your handling code here:
        jLabelKosongkanJadwalMisa.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jLabelKosongkanJadwalMisaMouseExited

    private void jLabelCariDataUmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCariDataUmatMouseClicked
        // TODO add your handling code here:
        new CariData().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jLabelCariDataUmatMouseClicked

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        int temp = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (temp == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new HalamanUtama().setVisible(true);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jLabelLihatDataUmatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLihatDataUmatMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LihatData().setVisible(true);
    }//GEN-LAST:event_jLabelLihatDataUmatMouseClicked

    private void jLabelTambahJadwalMisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTambahJadwalMisaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TambahJadwal().setVisible(true);
    }//GEN-LAST:event_jLabelTambahJadwalMisaMouseClicked

    private void jLabelHapusJadwalMisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHapusJadwalMisaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HapusJadwal().setVisible(true);
    }//GEN-LAST:event_jLabelHapusJadwalMisaMouseClicked

    private void jLabelKosongkanJadwalMisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKosongkanJadwalMisaMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new KosongkanJadwal().setVisible(true);
    }//GEN-LAST:event_jLabelKosongkanJadwalMisaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtamaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCariDataUmat;
    private javax.swing.JLabel jLabelHapusJadwalMisa;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelKosongkanJadwalMisa;
    private javax.swing.JLabel jLabelLihatDataUmat;
    private javax.swing.JLabel jLabelLogoHU;
    private javax.swing.JLabel jLabelLogoHU1;
    private javax.swing.JLabel jLabelTambahJadwalMisa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFormLogin;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaPanduan;
    // End of variables declaration//GEN-END:variables
}
