/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpus.app;

/**
 *
 * @author hertada
 */
public class dHelp extends javax.swing.JDialog {
    DaoPerpus dtperpus;


    public dHelp(java.awt.Frame parent, boolean modal,DaoPerpus dtperpus) {
        super(parent, modal);
        initComponents();
        this.dtperpus = dtperpus;
    }

    /**
     * Creates new form dHelp
     */
    public dHelp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bantuan Pengguna");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perpus/app/images/mcc.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Perpustakaan App merupakan platform untuk melatih \nmahasiswa Informatika Universitas Sanata Dharma \ntentang Pemrograman Berorientasi Obyek. Platform \nberdasarkan pada Apache NetBeans dari the Apache \nSoftware Foundation dan memiliki lisensi di bawah\nApache License Version 2.0.\n\nUntuk  informasi lebih lanjut silahkan mengunjungi : \n<o>website : http://www.mc.id.\n<o> email : support@mcc.id\n<o> IG : @mccid\n");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Isi Data (Peminjam, Koleksi, dan Transasi) Untuk Latihan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Product Version: Perpus Informatika 1.01\nUpdates: Updates not available\nJava: 14.0.2; Java 64-Bit VM 14.0.2+12-46\nRuntime: JRE 14.0.2+12-46\nSystem: Windows 10 version 10.0 \n\nThe Perpus Informatika and its user \ninterface are protected by trademark and\nother pending or exiting intellectual property\nrights in The United State of the Republic of\nIndonesia.\nCopy Left @mcc.id All Rights Reserved");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Peminjam dataPeminjam;
        dataPeminjam = new Dosen("D123", "Sujadmiko Raharjo", "Jl. Kembang Arum no.123 Condongcatur", 5, "19820325007");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Dosen("D124", "Bagong Ahmadi", "Jl. Proklamasi no.13 Caturtunggal", 5, "19800305012");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Dosen("D125", "Yohanes Supangat", "Jl. Ayam Jantan no.23X Maguwo Hardjo", 5, "19781225001");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Dosen("D126", "Alberta Sri Sumini", "Jl. Segi Tiga no.M88 Pakem", 5, "19730321006");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Dosen("D127", "John Sabar Menanti", "Gg. Kapuas no.L12 Mancasan Kidul", 5, "19990909009");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Dosen("D128", "Ayu Setianing Sekar", "Jl. Achmad Yani no.55 Blok I Komplek Kembang Jaya", 6, "19880818018");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Dosen("D129", "Citra Jesica Indah", "Jl. Pinus 5 no. 2 Cassa Grande", 5, "19850520003");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2015", "Rafael Mahesa Putra", "Jl. Sawo Matang no.133 Condongcatur", 3, "205314077");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2016", "Justino Ardian Suban Baolangu", "Gg. Kosan Indah Paingan Maguwoharjo", 3, "205314079");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2017", "Gabriel Advent Batan", "Gg. Programming no.1010 Desa Java", 3, "205314096");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2018", "Mario Richard Paulo Yamlean", "Jl. Apache Netbeans  no.12B Oracle Black Street 5th", 3, "205314104");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2019", "Katrina Yuliana Kartika", "Gg. Inheritance no.77 Desa Object Oriented II", 4, "205314099");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2020", "Marcelia Putri Supriosa", "Jl. Graphical User Interface no.1 Kampung Java Component 2th", 3, "205314075");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Mahasiswa("M2021", "Bernadetha Mega Devina Ayuningtyas", "Gg. Exception Personal no.2X Wall of Error II ", 4, "195314058");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Umum("U8810", "Chelsea Olivia", "Gg. Anak Jalanan no.2X The World of the Married", 4, "3404070802756001");
        dtperpus.isiDataPeminjam(dataPeminjam);
         dataPeminjam = new Umum("U8811", "Raffi Ahmad", "Jl. Ikatan Cinta no.8 SKY Castle 2th", 4, "3404080702156006");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Umum("U8812", "Kevin Julio", "Gg. Ganteng ganteng Srigala no.11 Crash Landing on You ", 4, "3404070305875004");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Umum("U8813", "Ayu Ting Ting", "Jl. Cinta Fitri no.8A The World of the Married", 4, "5404080804758009");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Umum("U8814", "Prilly Latuconsina", "Gg. Intan no.25 Squid Gam", 4, "4404080602776003");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Umum("U8815", "Via Valen", "Gg. Putri Yang Ditukar no.9 Dali and Cocky Prince", 4, "3404071205756012");
        dtperpus.isiDataPeminjam(dataPeminjam);
        dataPeminjam = new Umum("U8816", "Gisella Anastasia", "Gg. Preman Pensiun no.99 The Good Detective", 4, "3404071112957021");
        dtperpus.isiDataPeminjam(dataPeminjam);

        Koleksi dataKoleksi;
        dataKoleksi = new Disk("D12345", "Legendary Toefl Test Of English", "Sealova Media", Boolean.TRUE, "MP4", "9799483530");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Disk("D12346", "Getting To Yes", "Gramedia Pustaka Utama", Boolean.TRUE, "DVD", "9789792271973");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Disk("D12347", "Cumsumer Behavior Hoyer Macinnis", "Mc GrawHill", Boolean.TRUE, "MP4", "9780324834277");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Disk("D12348", "Men Are from Mars Women Are from Venus", "Andi Offset", Boolean.FALSE, "BLUERAY", "9786020375212");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Disk("D12349", "The Ancient Chinese Wisdom Sc", "Tiga Serangkai", Boolean.TRUE, "MP4", "9789792291827");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Disk("D12350", "The Art of War ", "Pustaka Karya", Boolean.TRUE, "MP4", "9786020333465");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Disk("D12351", "X-Men Mutant Genesis 2.0 HC", "Wiley Press", Boolean.TRUE, "CDAUDIO", "9780785163589");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56789", "Algoritma dan Pemrograman", "Informatika", Boolean.TRUE, 770, "6021514917");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56790", "Pemrograman C dan C plus plus", "Informatika", Boolean.TRUE, 290, "8221514787");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56791", "Algoritma dan Pemrograman", "Informatika", Boolean.TRUE, 770, "6021514917");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56792", "Pemrograman Berbasis Mobile Menggunakan Android Studio", "Deepublish", Boolean.FALSE, 550, "9786024016272");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56793", "Konsep dan Implementasi Pemrograman Laravel 7", "Lokomedia", Boolean.TRUE, 665, "9860240124917");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56794", "Pemrograman Mikrokontroler AVR Bahasa Assemby dan C", "Media Online", Boolean.TRUE, 780, "235648514917");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Buku("B56795", "Esensi Bahasa Pemrograman Java", "Kodebuku", Boolean.FALSE, 770, "68948775215");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695847", "Infokomputer", "Infomedia", Boolean.FALSE, 12, 2, "21253658984");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695848", "Tempo", "Tempo Press", Boolean.FALSE, 12, 2, "212536845758");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695849", "Trubus", "Gramedia Print", Boolean.FALSE, 12, 2, "54255788548");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695850", "Art Projects", "Artis Press", Boolean.TRUE, 12, 2, "62548799521");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695851", "Elektron", "Elek Media", Boolean.FALSE, 12, 2, "356548745522");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695852", "PCPlus", "Media Indonesia", Boolean.TRUE, 12, 2, "45488784512");
        dtperpus.isiDataKoleksi(dataKoleksi);
        dataKoleksi = new Majalah("M695853", "CHIP", "Softart Inc", Boolean.FALSE, 12, 2, "98765215487");
        dtperpus.isiDataKoleksi(dataKoleksi);
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dHelp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
