package JDBC2;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SIM extends javax.swing.JFrame {

    /**
     * Creates new form SIM
     */
    public SIM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuShowData = new javax.swing.JMenu();
        jMenuItemShowData = new javax.swing.JMenuItem();
        jMenuItemInsertData = new javax.swing.JMenuItem();
        jMenuItemUpdateData = new javax.swing.JMenuItem();
        jMenuItemDeleteData = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Mahasiswa");

        jMenuShowData.setText("Edit");
        jMenuShowData.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jMenuItemShowData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItemShowData.setText("Show Data");
        jMenuItemShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemShowDataActionPerformed(evt);
            }
        });
        jMenuShowData.add(jMenuItemShowData);

        jMenuItemInsertData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItemInsertData.setText("Insert Data");
        jMenuItemInsertData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertDataActionPerformed(evt);
            }
        });
        jMenuShowData.add(jMenuItemInsertData);

        jMenuItemUpdateData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItemUpdateData.setText("Update Data");
        jMenuItemUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateDataActionPerformed(evt);
            }
        });
        jMenuShowData.add(jMenuItemUpdateData);

        jMenuItemDeleteData.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItemDeleteData.setText("Delete Data");
        jMenuItemDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteDataActionPerformed(evt);
            }
        });
        jMenuShowData.add(jMenuItemDeleteData);
        jMenuShowData.add(jSeparator1);

        jMenuItemExit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuShowData.add(jMenuItemExit);

        jMenuBar1.add(jMenuShowData);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertDataActionPerformed
        // TODO add your handling code here:
        InsertData insert = new InsertData();
        insert.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemInsertDataActionPerformed

    private void jMenuItemDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteDataActionPerformed
        // TODO add your handling code here:
        DeleteData delete = new DeleteData();
        delete.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemDeleteDataActionPerformed

    private void jMenuItemShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemShowDataActionPerformed
        // TODO add your handling code here:
        ShowData show = null;
        try {
            show = new ShowData();
        } catch (SQLException ex) {
            Logger.getLogger(SIM.class.getName()).log(Level.SEVERE, null, ex);
        }
        show.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemShowDataActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateDataActionPerformed
        // TODO add your handling code here:
        UpdateData update = new UpdateData();
        update.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemUpdateDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDeleteData;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemInsertData;
    private javax.swing.JMenuItem jMenuItemShowData;
    private javax.swing.JMenuItem jMenuItemUpdateData;
    private javax.swing.JMenu jMenuShowData;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
